name: NodeJS with Webpack

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Build
        run: |
          npm install -y
          npx webpack

      - name: Add shebang and make executable
        run: |
          (echo "#!/usr/bin/env node"; cat dist/bundle.js) > tmp
          mv tmp dist/bundle.js
          chmod u+x dist/bundle.js

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist
